Repository haddocking/haddock3, pull requests merged in 2021-11, with the labels that each got.

#81 Implements dedicated configuration reader
  examples/docking/docking.cfg
  examples/scoring/only_scoring.toml
  examples/scoring/scoring.cfg
  examples/thirdparty/gdock/gdock-integration.cfg
  examples/thirdparty/lightdock/lightdock.cfg
  requirements.txt
  requirements.yml
  src/haddock/gear/config_reader.py
  src/haddock/gear/parameters.py
  src/haddock/gear/prepare_run.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/__init__.py
  src/haddock/modules/analysis/clustfcc/__init__.py
  src/haddock/modules/analysis/clustfcc/defaults.cfg
  src/haddock/modules/analysis/seletop/__init__.py
  src/haddock/modules/analysis/seletop/defaults.cfg
  src/haddock/modules/analysis/seletopclusts/__init__.py
  src/haddock/modules/analysis/seletopclusts/defaults.cfg
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/emref/defaults.cfg
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/flexref/defaults.cfg
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/refinement/mdref/defaults.cfg
  src/haddock/modules/sampling/gdock/__init__.py
  src/haddock/modules/sampling/gdock/defaults.cfg
  src/haddock/modules/sampling/lightdock/__init__.py
  src/haddock/modules/sampling/lightdock/defaults.cfg
  src/haddock/modules/sampling/rigidbody/__init__.py
  src/haddock/modules/sampling/rigidbody/defaults.cfg
  src/haddock/modules/scoring/emscoring/__init__.py
  src/haddock/modules/scoring/emscoring/defaults.cfg
  src/haddock/modules/topology/topoaa/__init__.py
  src/haddock/modules/topology/topoaa/defaults.cfg
  src/haddock/modules/topology/topocg/__init__.py
  src/haddock/modules/topology/topocg/defaults.cfg
  tests/test_config_reader.py
  tests/test_examples_general.py
  tests/test_modules_general.py
Labels: enhancement

#104 Removes the need for `activate_haddock` global variables setup
  README.md
  bin/activate_haddock
  examples/docking/docking.cfg
  examples/thirdparty/gdock/gdock-integration.cfg
  examples/thirdparty/lightdock/lightdock.cfg
  src/haddock/__init__.py
  src/haddock/core/defaults.py
  src/haddock/gear/prepare_run.py
  src/haddock/libs/libsubprocess.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/__init__.py
  src/haddock/modules/analysis/clustfcc/__init__.py
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/sampling/gdock/__init__.py
  src/haddock/modules/sampling/lightdock/__init__.py
  src/haddock/modules/sampling/rigidbody/__init__.py
  src/haddock/modules/scoring/emscoring/__init__.py
  src/haddock/modules/topology/topoaa/__init__.py
Labels: enhancement

#107 Corrects for the rare case of number of CPUs = 0
  src/haddock/libs/libutil.py
Labels: bug

#109 Removes remaining toml dependency after #81
  src/haddock/gear/config_reader.py
  src/haddock/modules/analysis/clustfcc/__init__.py
Labels: enhancement

#110 Implements CI for python modules
  .bumpversion.cfg
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/py310.yml
  .github/workflows/py38.yml
  .github/workflows/py39.yml
  CHANGELOG.md
  CONTRIBUTING.md
  INSTALL.md
  MANIFEST.in
  README.md
  README.rst
  devtools/clean_dist_check.py
  install-thirdparty.md
  requirements.txt
  requirements.yml
  setup.py
  src/haddock/__init__.py
  src/haddock/clis/cli.py
  tox.ini
Labels: CI / repository

#111 remove py310 action and env
  .github/workflows/py310.yml
  setup.py
  tox.ini
Labels: bug

#106 Updates the logging system
  src/haddock/__init__.py
  src/haddock/clis/cli.py
  src/haddock/core/defaults.py
  src/haddock/gear/greetings.py
  src/haddock/gear/prepare_run.py
  src/haddock/libs/liblog.py
  src/haddock/libs/libparallel.py
  src/haddock/libs/libutil.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/__init__.py
  src/haddock/modules/analysis/clustfcc/__init__.py
  src/haddock/modules/analysis/seletop/__init__.py
  src/haddock/modules/analysis/seletopclusts/__init__.py
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/sampling/gdock/__init__.py
  src/haddock/modules/sampling/lightdock/__init__.py
  src/haddock/modules/sampling/rigidbody/__init__.py
  src/haddock/modules/scoring/emscoring/__init__.py
  src/haddock/modules/topology/topoaa/__init__.py
  tests/test_liblog.py
  tests/test_libutil.py
Labels: enhancement

#105 Improves Scheduler `ctrl+c` handling
  src/haddock/libs/libparallel.py
  src/haddock/libs/libsubprocess.py
  src/haddock/libs/libworkflow.py
  tests/test_exceptions.py
Labels: enhancement

#112 Corrects var names critical errors
  src/haddock/gear/greetings.py
  src/haddock/libs/libworkflow.py
Labels: bug

#114 Codecoving
  .github/workflows/py38.yml
  .github/workflows/py39.yml
Labels: CI / repository

#113 Lints the code so far
  setup.py
  src/haddock/__init__.py
  src/haddock/clis/cli.py
  src/haddock/core/defaults.py
  src/haddock/core/exceptions.py
  src/haddock/gear/__init__.py
  src/haddock/gear/config_reader.py
  src/haddock/gear/greetings.py
  src/haddock/gear/haddockmodel.py
  src/haddock/gear/prepare_run.py
  src/haddock/gear/restart_run.py
  src/haddock/libs/libcns.py
  src/haddock/libs/liblog.py
  src/haddock/libs/libmath.py
  src/haddock/libs/libontology.py
  src/haddock/libs/libparallel.py
  src/haddock/libs/libpdb.py
  src/haddock/libs/libstructure.py
  src/haddock/libs/libsubprocess.py
  src/haddock/libs/libutil.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/__init__.py
  src/haddock/modules/analysis/__init__.py
  src/haddock/modules/analysis/clustfcc/__init__.py
  src/haddock/modules/analysis/seletop/__init__.py
  src/haddock/modules/analysis/seletopclusts/__init__.py
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/sampling/__init__.py
  src/haddock/modules/sampling/gdock/__init__.py
  src/haddock/modules/sampling/lightdock/__init__.py
  src/haddock/modules/sampling/rigidbody/__init__.py
  src/haddock/modules/scoring/__init__.py
  src/haddock/modules/scoring/emscoring/__init__.py
  src/haddock/modules/topology/__init__.py
  src/haddock/modules/topology/topoaa/__init__.py
  src/haddock/modules/topology/topocg/__init__.py
  tests/test_cli.py
  tests/test_config_reader.py
  tests/test_examples_general.py
  tests/test_exceptions.py
  tests/test_gear_restart.py
  tests/test_liblog.py
  tests/test_libutil.py
  tests/test_modules_general.py
  tox.ini
Labels: enhancement

#115 removed py310 from tox
  tox.ini
Labels: CI / repository

#129 Models start 1-index
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/sampling/rigidbody/__init__.py
Labels: enhancement

#130 Implement `caprieval`
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/py38.yml
  requirements.txt
  requirements.yml
  setup.py
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/caprieval/defaults.cfg
  tox.ini
Labels: enhancement, CI / repository

#137 Correct enumerate syntax
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/topology/topoaa/__init__.py
Labels: bug

#136 Adds support for global variables for CNS
  src/haddock/gear/prepare_run.py
  src/haddock/libs/libsubprocess.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/sampling/rigidbody/__init__.py
  src/haddock/modules/scoring/emscoring/__init__.py
  src/haddock/modules/topology/topoaa/__init__.py
Labels: enhancement

#145 Added example, some cns module corrections/additions
  examples/docking-protein-protein/data/e2a-hpr_1GGR.pdb
  examples/docking-protein-protein/data/e2a-hpr_air.tbl
  examples/docking-protein-protein/data/e2aP_1F3G.pdb
  examples/docking-protein-protein/data/hpr_ensemble.pdb
  examples/docking-protein-protein/data/hpr_ensemble_1.pdb
  examples/docking-protein-protein/data/hpr_ensemble_10.pdb
  examples/docking-protein-protein/data/hpr_ensemble_2.pdb
  examples/docking-protein-protein/data/hpr_ensemble_3.pdb
  examples/docking-protein-protein/data/hpr_ensemble_4.pdb
  examples/docking-protein-protein/data/hpr_ensemble_5.pdb
  examples/docking-protein-protein/data/hpr_ensemble_6.pdb
  examples/docking-protein-protein/data/hpr_ensemble_7.pdb
  examples/docking-protein-protein/data/hpr_ensemble_8.pdb
  examples/docking-protein-protein/data/hpr_ensemble_9.pdb
  examples/docking-protein-protein/docking-protein-protein.cfg
  src/haddock/modules/refinement/flexref/cns/protein-ss-restraints-all.cns
  src/haddock/modules/refinement/flexref/cns/protein-ss-restraints-alpha-beta.cns
  src/haddock/modules/refinement/flexref/cns/protein-ss-restraints-alpha.cns
  src/haddock/modules/sampling/rigidbody/cns/rigidbody.cns
Labels: feature

#147 Bugfix `caprieval`
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/caprieval/defaults.cfg
Labels: bug

#150 Solves missing repeated modules during `prepare_run`
  src/haddock/gear/prepare_run.py
Labels: bug

#155 Fixes arrays being overwritten in `caprieval`
  src/haddock/modules/analysis/caprieval/__init__.py
Labels: bug
