Repository haddocking/haddock3, pull requests merged in 2021-12, with the labels that each got.

#163 `None` variables are NOT written to CNS
  src/haddock/libs/libcns.py
  src/haddock/libs/libutil.py
  src/haddock/modules/__init__.py
  src/haddock/modules/topology/topoaa/__init__.py
Labels: bug, enhancement

#167 improves on #163
  src/haddock/libs/libcns.py
  src/haddock/libs/libfunc.py
  tests/test_libcns.py
Labels: enhancement

#168 empty strings are written to CNS
  src/haddock/libs/libcns.py
  tests/test_libcns.py
Labels: bug

#169 `input` params in `topoaa/defaults.cfg` now with proper behaviour
  src/haddock/libs/libcns.py
  src/haddock/libs/libpdb.py
  src/haddock/libs/libutil.py
  src/haddock/modules/topology/topoaa/__init__.py
  tests/test_libutil.py
Labels: enhancement

#170 Added protein-ligand-shape example
  examples/docking-protein-DNA/data/dna.pdb
  examples/docking-protein-homotrimer/docking-protein-homotrimer.cfg
  examples/docking-protein-ligand-shape/data/3DV1-fit-prot.pdb
  examples/docking-protein-ligand-shape/data/ligand-ensemble.pdb
  examples/docking-protein-ligand-shape/data/ligand.param
  examples/docking-protein-ligand-shape/data/ligand.top
  examples/docking-protein-ligand-shape/data/shape-restraints-from-shape-1.tbl
  examples/docking-protein-ligand-shape/data/shape.pdb
  examples/docking-protein-ligand-shape/data/target.pdb
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape.cfg
  examples/docking-protein-ligand/docking-protein-ligand.cfg
  examples/docking-protein-peptide/docking-protein-peptide.cfg
  examples/docking-protein-protein/docking-protein-protein-mdref.cfg
  examples/docking-protein-protein/docking-protein-protein.cfg
  examples/docking/docking.cfg
  src/haddock/cns/toppar/haddock.top
  src/haddock/modules/refinement/emref/cns/emref.cns
  src/haddock/modules/refinement/emref/cns/read_param.cns
  src/haddock/modules/refinement/flexref/cns/flexref.cns
  src/haddock/modules/refinement/flexref/cns/read_param.cns
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/refinement/mdref/cns/mdref.cns
  src/haddock/modules/refinement/mdref/cns/read_param.cns
  src/haddock/modules/refinement/mdref/cns/restrain-ions.cns
  src/haddock/modules/sampling/rigidbody/cns/read_param.cns
  src/haddock/modules/sampling/rigidbody/cns/rigidbody.cns
  src/haddock/modules/topology/topoaa/cns/generate-topology.cns
  src/haddock/modules/topology/topoaa/defaults.cfg
Labels: enhancement

#174 Improves regex for scientific notation in config reader
  src/haddock/gear/config_reader.py
  tests/test_config_reader.py
Labels: bug, enhancement

#175 Added check to make sure the seed file is present before reading.
  src/haddock/modules/refinement/emref/cns/emref.cns
  src/haddock/modules/refinement/flexref/cns/flexref.cns
  src/haddock/modules/refinement/mdref/cns/mdref.cns
Labels: enhancement

#182 Add option to "sortby" in `caprieval`
  requirements.txt
  requirements.yml
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/caprieval/defaults.cfg
Labels: enhancement

#159 Change log statements
  src/haddock/libs/liblog.py
  src/haddock/libs/libparallel.py
  src/haddock/libs/libutil.py
  src/haddock/modules/__init__.py
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/clustfcc/__init__.py
  src/haddock/modules/analysis/seletop/__init__.py
  src/haddock/modules/analysis/seletopclusts/__init__.py
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/sampling/gdock/__init__.py
  src/haddock/modules/sampling/lightdock/__init__.py
  src/haddock/modules/sampling/rigidbody/__init__.py
  src/haddock/modules/scoring/emscoring/__init__.py
  src/haddock/modules/topology/topoaa/__init__.py
Labels: enhancement, documentation

#116 Benchmarking system and configuration.
  docs/benchmark-tut.md
  setup.py
  src/haddock/clis/cli_bm.py
  src/haddock/clis/cli_dmn.py
  tox.ini
Labels: CI / repository

#185 Add option to sort-by in `caprieval`
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/caprieval/defaults.cfg
Labels: feature

#192 Implement HPC execution
  examples/docking-protein-protein/docking-protein-protein-hpc.cfg
  src/haddock/clis/cli_bm.py
  src/haddock/libs/libhpc.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/__init__.py
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/sampling/rigidbody/__init__.py
  src/haddock/modules/topology/topoaa/__init__.py
Labels: feature

#193 Fix HPC completed percentage
  src/haddock/libs/libhpc.py
Labels: bug

#203 Updates clarifies install instructions
  INSTALL.md
Labels: documentation

#191 Do not delete the run dir.
  src/haddock/gear/greetings.py
  src/haddock/gear/prepare_run.py
Labels: enhancement

#214 Export environment variables to a file per module.
  src/haddock/libs/libparallel.py
  src/haddock/libs/libsubprocess.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/__init__.py
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/sampling/rigidbody/__init__.py
  src/haddock/modules/scoring/emscoring/__init__.py
  src/haddock/modules/topology/topoaa/__init__.py
Labels: feature

#218 Starts using `flake8-print`
  tox.ini
Labels: CI / repository

#226 Edit `libhpc` with new variable scheme
  src/haddock/libs/libhpc.py
Labels: bug

#234 Sort models from previous module by score in `caprieval`
  src/haddock/modules/analysis/caprieval/__init__.py
Labels: bug

#237 fix `caprieval` reading from the wrong reslist when assembling the numbering reference
  src/haddock/modules/analysis/caprieval/capri.py
Labels: bug

#219 Use `data` dir to store input data and point relative paths
  examples/docking-protein-DNA/docking-protein-DNA.cfg
  examples/docking-protein-homotrimer/docking-protein-homotrimer.cfg
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape.cfg
  examples/docking-protein-ligand/docking-protein-ligand.cfg
  examples/docking-protein-peptide/docking-protein-peptide.cfg
  examples/docking-protein-protein/docking-protein-protein-hpc.cfg
  examples/docking-protein-protein/docking-protein-protein-mdref.cfg
  examples/docking-protein-protein/docking-protein-protein.cfg
  examples/refine-complex/refine-complex.cfg
  src/haddock/clis/cli.py
  src/haddock/core/cns_paths.py
  src/haddock/gear/config_reader.py
  src/haddock/gear/parameters.py
  src/haddock/gear/prepare_run.py
  src/haddock/libs/libcns.py
  src/haddock/libs/libio.py
  src/haddock/libs/libontology.py
  src/haddock/libs/libpdb.py
  src/haddock/libs/libstructure.py
  src/haddock/libs/libsubprocess.py
  src/haddock/libs/libutil.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/__init__.py
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/caprieval/capri.py
  src/haddock/modules/analysis/caprieval/defaults.cfg
  src/haddock/modules/analysis/clustfcc/__init__.py
  src/haddock/modules/analysis/seletop/__init__.py
  src/haddock/modules/analysis/seletopclusts/__init__.py
  src/haddock/modules/base_cns_module.py
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/sampling/gdock/__init__.py
  src/haddock/modules/sampling/lightdock/__init__.py
  src/haddock/modules/sampling/rigidbody/__init__.py
  src/haddock/modules/scoring/emscoring/__init__.py
  src/haddock/modules/topology/topoaa/__init__.py
  tests/test_config_reader.py
  tests/test_libcns.py
Labels: enhancement
