Repository haddocking/haddock3, pull requests merged in 2022-06, with the labels that each got.

#455 Update `MANIFEST.in`
  MANIFEST.in
Labels: CI / repository

#454 Enhance clustering protocols
  src/haddock/modules/analysis/clustfcc/__init__.py
  src/haddock/modules/analysis/seletopclusts/__init__.py
Labels: enhancement, m|clustfcc, m|seletopclusts

#460 amended clt_threshold behavior
  src/haddock/modules/analysis/caprieval/capri.py
  tests/test_module_caprieval.py
Labels: bug, m|caprieval

#450 Populate `mol_` expandable parameters when using `--extend-run`
  src/haddock/gear/expandable_parameters.py
  src/haddock/modules/__init__.py
  src/haddock/modules/base_cns_module.py
  tests/test_gear_expandable_parameters.py
Labels: bug

#439 Allows single entries in `molecules` parameter
  src/haddock/gear/prepare_run.py
  tests/test_gear_prepare_run.py
Labels: enhancement

#462 add cluster name to `seletopclusts.txt`
  src/haddock/modules/analysis/seletopclusts/__init__.py
Labels: m|seletopclusts

#461 add tests to `topoaa`
  src/haddock/modules/topology/topoaa/__init__.py
  tests/golden_data/ens_header.pdb
  tests/test_module_topoaa.py
Labels: m|topoaa, :godmode:

#463 add haddock3-docs to .gitignore
  .gitignore
Labels: CI / repository

#465 remove duplicated entry in `clustfcc.txt`
  src/haddock/modules/analysis/clustfcc/__init__.py
Labels: bug, m|clustfcc

#467 Corrects bug in `--restart` option
  src/haddock/gear/prepare_run.py
Labels: bug, :snake: workflow

#471 Add missing header to `seletopclusts.txt`
  src/haddock/modules/analysis/seletopclusts/__init__.py
Labels: bug, m|seletopclusts

#468 Implements clean output - compress/archive output files
  docs/clients/cliclean.rst
  docs/clients/cliunpack.rst
  docs/clients/index.rst
  docs/reference/gear/clean_steps.rst
  docs/reference/gear/index.rst
  setup.py
  src/haddock/clis/cli.py
  src/haddock/clis/cli_clean.py
  src/haddock/clis/cli_unpack.py
  src/haddock/gear/clean_steps.py
  src/haddock/gear/extend_run.py
  src/haddock/gear/prepare_run.py
  src/haddock/libs/libcli.py
  src/haddock/libs/libio.py
  src/haddock/libs/libtimer.py
  src/haddock/libs/libutil.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/__init__.py
  src/haddock/modules/defaults.yaml
  tests/__init__.py
  tests/clean_output_data/run1/0_topoaa/params.cfg
  tests/clean_output_data/run1/0_topoaa/structure_1.inp
  tests/clean_output_data/run1/0_topoaa/structure_1.out
  tests/clean_output_data/run1/0_topoaa/structure_1.pdb
  tests/clean_output_data/run1/0_topoaa/structure_1.psf
  tests/clean_output_data/run1/1_rigidbody/io.json
  tests/clean_output_data/run1/1_rigidbody/params.cfg
  tests/clean_output_data/run1/1_rigidbody/structure_1.inp
  tests/clean_output_data/run1/1_rigidbody/structure_1.out
  tests/clean_output_data/run1/1_rigidbody/structure_1.pdb
  tests/clean_output_data/run1/1_rigidbody/structure_1.seed
  tests/clean_output_data/run1/1_rigidbody/structure_2.inp
  tests/clean_output_data/run1/1_rigidbody/structure_2.out
  tests/clean_output_data/run1/1_rigidbody/structure_2.pdb
  tests/clean_output_data/run1/1_rigidbody/structure_2.seed
  tests/clean_output_data/run1/2_clustfcc/structure_1.con
  tests/clean_output_data/run1/2_clustfcc/structure_2.con
  tests/test_gear_clean_steps.py
  tests/test_libio.py
  tests/test_libtimer.py
  tests/test_libutil.py
  tests/test_modules_general.py
Labels: enhancement

#477 Corrects check modules names in config on startup
  src/haddock/gear/prepare_run.py
Labels: bug, :snake: workflow

#478 Update CI workflows
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  CONTRIBUTING.md
  README.md
  tox.ini
Labels: CI / repository

#475 Improve reading `md5` from `REMARK` lines
  src/haddock/modules/topology/topoaa/__init__.py
Labels: bug, m|topoaa

#474 Allows `topoaa` to run in different parts of the workflow
  src/haddock/libs/libpdb.py
  src/haddock/libs/libstructure.py
  src/haddock/modules/topology/topoaa/__init__.py
Labels: feature, m|topoaa

#481 Improves mandatory parameter check
  src/haddock/gear/prepare_run.py
  src/haddock/modules/topology/topoaa/defaults.yaml
  tests/test_module_topoaa.py
Labels: bug, enhancement, :snake: workflow

#486 added single linkage as clustrmsd default
  examples/docking-protein-ligand/docking-protein-ligand-test.cfg
  src/haddock/modules/analysis/clustrmsd/defaults.yaml
  tests/test_module_clustrmsd.py
Labels: m|clustrmsd

#484 run analysis modules after topoaa
  examples/analysis/data/ensemble_4G6M.pdb
  examples/analysis/data/target.pdb
  examples/analysis/topoaa-caprieval-test.cfg
  examples/analysis/topoaa-clustfcc-test.cfg
  examples/analysis/topoaa-rmsdmatrix-clustrmsd-test.cfg
  examples/compare_runs.py
  examples/run_tests.py
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/clustfcc/__init__.py
  src/haddock/modules/analysis/rmsdmatrix/__init__.py
Labels: enhancement, m|topoaa

#476 Add general parameters to `haddock3-cfg` client
  src/haddock/clis/cli_cfg.py
  src/haddock/gear/yaml2cfg.py
  tests/__init__.py
  tests/configs/yaml2cfg_converted_no_header.cfg
  tests/test_cli_cfg.py
  tests/test_gear_yaml2cfg.py
Labels: enhancement

#490 Improve two titles in documentation
  docs/examples.md
  docs/tutorials/index.rst
Labels: documentation
