Repository haddocking/haddock3, pull requests merged in 2022-05, with the labels that each got.

#419 updates CI to flake8-print v5
  examples/compare_runs.py
  examples/run_tests.py
  src/haddock/clis/cli_cfg.py
  tox.ini
Labels: CI / repository

#418 Additional unit tests and newline improvements in `config_writer`
  src/haddock/gear/config_writer.py
  tests/test_gear_config_writer.py
  tests/test_modules_general.py
Labels: enhancement, enhance user experience, :scroll:, :godmode:, :snake: workflow

#420 Correct minor typo
  tests/test_modules_general.py
Labels: CI / repository

#423 Reduce `pytest` verbosity
  CONTRIBUTING.md
  tox.ini
Labels: CI / repository

#424 update `pdb-tools version` to `2.4.5`
  requirements.txt
  requirements.yml
Labels: CI / repository

#414 Implement RMSD clustering and matrix analysis modules
  docs/conf.py
  docs/modules/analysis/clustrmsd.rst
  docs/modules/analysis/index.rst
  docs/modules/analysis/rmsdmatrix.rst
  examples/docking-protein-ligand/docking-protein-ligand-test.cfg
  requirements.txt
  requirements.yml
  src/haddock/gear/prepare_run.py
  src/haddock/libs/libontology.py
  src/haddock/modules/__init__.py
  src/haddock/modules/analysis/__init__.py
  src/haddock/modules/analysis/clustrmsd/__init__.py
  src/haddock/modules/analysis/clustrmsd/clustrmsd.py
  src/haddock/modules/analysis/clustrmsd/defaults.yaml
  src/haddock/modules/analysis/rmsdmatrix/__init__.py
  src/haddock/modules/analysis/rmsdmatrix/defaults.yaml
  src/haddock/modules/analysis/rmsdmatrix/rmsd.py
  tests/test_module_clustrmsd.py
  tests/test_module_rmsdmatrix.py
Labels: feature, m|clustrmsd, m|rmsdmatrix

#427 Improves method to find step folders in a run directory
  src/haddock/core/defaults.py
  src/haddock/gear/restart_run.py
  src/haddock/modules/__init__.py
  tests/test_modules_general.py
Labels: enhancement

#428 Corrects bug in `--restart`
  examples/run_tests.py
  src/haddock/gear/restart_run.py
  src/haddock/libs/libutil.py
Labels: bug

#430 Test module clustfcc
  tests/test_module_clustfcc.py
Labels: m|clustfcc, :godmode:

#429 rename `--start-from-copy` to `--extend-run`
  docs/reference/gear/extend_run.rst
  docs/reference/gear/index.rst
  docs/tutorials/continuing_runs.md
  examples/compare_runs.py
  examples/run_tests.py
  src/haddock/clis/cli.py
  src/haddock/clis/cli_cp.py
  src/haddock/gear/extend_run.py
  src/haddock/gear/prepare_run.py
  tests/test_extend_run.py
Labels: enhance user experience, :snake: workflow

#431 Geometry library
  docs/reference/libs/index.rst
  docs/reference/libs/libalign.rst
  src/haddock/libs/libalign.py
  src/haddock/modules/analysis/caprieval/capri.py
  src/haddock/modules/analysis/rmsdmatrix/rmsd.py
  tests/test_libalign.py
  tests/test_module_caprieval.py
Labels: m|caprieval, refactors, :scroll:, m|rmsdmatrix

#434 Changed some parameters to hidden
  src/haddock/modules/refinement/flexref/defaults.yaml
Labels: m|flexref

#435 Update README file for Beta version
  README.md
  tox.ini
Labels: documentation

#441 Refactor `caprieval`
  src/haddock/libs/libalign.py
  src/haddock/libs/libio.py
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/caprieval/capri.py
  src/haddock/modules/analysis/caprieval/caprijob.py
  src/haddock/modules/analysis/rmsdmatrix/rmsd.py
  tests/test_libalign.py
  tests/test_libio.py
  tests/test_module_caprieval.py
Labels: m|caprieval, refactors

#436 Generate `.rst` documentation page for `.yaml` default configuration files
  .gitignore
  .readthedocs.yml
  devtools/build_defaults_rst.py
  devtools/docs-requirements.txt
  docs/conf.py
  docs/modules/analysis/caprieval.rst
  docs/modules/analysis/clustfcc.rst
  docs/modules/analysis/clustrmsd.rst
  docs/modules/analysis/rmsdmatrix.rst
  docs/modules/analysis/seletop.rst
  docs/modules/analysis/seletopclusts.rst
  docs/modules/index.rst
  docs/modules/refinement/emref.rst
  docs/modules/refinement/flexref.rst
  docs/modules/refinement/mdref.rst
  docs/modules/sampling/gdock.rst
  docs/modules/sampling/lightdock.rst
  docs/modules/sampling/rigidbody.rst
  docs/modules/scoring/emscoring.rst
  docs/modules/scoring/mdscoring.rst
  docs/modules/topology/topoaa.rst
  docs/reference/core/index.rst
  tox.ini
Labels: documentation, :scroll:

#445 Add user documentation on configuration files
  docs/reference/gear/config_reader.rst
  docs/reference/gear/config_writer.rst
  docs/tutorials/index.rst
  docs/tutorials/user_config.rst
  src/haddock/gear/config_reader.py
  src/haddock/gear/config_writer.py
  src/haddock/modules/__init__.py
Labels: documentation, :scroll:
