Repository haddocking/haddock3, pull requests merged in 2022-02, with the labels that each got.

#301 Correct `libhpc.HPCScheduler` defaults
  src/haddock/libs/libhpc.py
Labels: bug

#274 Convert `default.cfg` to YAML files
  requirements.txt
  requirements.yml
  setup.py
  src/haddock/__init__.py
  src/haddock/clis/cli_cfg.py
  src/haddock/gear/prepare_run.py
  src/haddock/gear/yaml2cfg.py
  src/haddock/libs/libhpc.py
  src/haddock/libs/libio.py
  src/haddock/modules/__init__.py
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/caprieval/defaults.cfg
  src/haddock/modules/analysis/caprieval/defaults.yaml
  src/haddock/modules/analysis/clustfcc/__init__.py
  src/haddock/modules/analysis/clustfcc/defaults.cfg
  src/haddock/modules/analysis/clustfcc/defaults.yaml
  src/haddock/modules/analysis/seletop/__init__.py
  src/haddock/modules/analysis/seletop/defaults.cfg
  src/haddock/modules/analysis/seletop/defaults.yaml
  src/haddock/modules/analysis/seletopclusts/__init__.py
  src/haddock/modules/analysis/seletopclusts/defaults.cfg
  src/haddock/modules/analysis/seletopclusts/defaults.yaml
  src/haddock/modules/defaults.cfg
  src/haddock/modules/defaults.yaml
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/emref/defaults.cfg
  src/haddock/modules/refinement/emref/defaults.yaml
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/flexref/defaults.cfg
  src/haddock/modules/refinement/flexref/defaults.yaml
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/refinement/mdref/defaults.cfg
  src/haddock/modules/refinement/mdref/defaults.yaml
  src/haddock/modules/sampling/gdock/__init__.py
  src/haddock/modules/sampling/gdock/defaults.cfg
  src/haddock/modules/sampling/gdock/defaults.yaml
  src/haddock/modules/sampling/lightdock/__init__.py
  src/haddock/modules/sampling/lightdock/defaults.cfg
  src/haddock/modules/sampling/lightdock/defaults.yaml
  src/haddock/modules/sampling/rigidbody/__init__.py
  src/haddock/modules/sampling/rigidbody/defaults.cfg
  src/haddock/modules/sampling/rigidbody/defaults.yaml
  src/haddock/modules/scoring/emscoring/__init__.py
  src/haddock/modules/scoring/emscoring/defaults.cfg
  src/haddock/modules/scoring/emscoring/defaults.yaml
  src/haddock/modules/topology/topoaa/__init__.py
  src/haddock/modules/topology/topoaa/cns/generate-topology.cns
  src/haddock/modules/topology/topoaa/defaults.cfg
  src/haddock/modules/topology/topoaa/defaults.yaml
  src/haddock/modules/topology/topocg/__init__.py
  src/haddock/modules/topology/topocg/defaults.cfg
  src/haddock/modules/topology/topocg/defaults.yaml
  tests/__init__.py
  tests/configs/yaml2cfg_converted.cfg
  tests/configs/yml_example.yml
  tests/test_modules_general.py
  tests/test_yaml2cfg.py
Labels: feature, documentation, enhance user experience

#306 Correct `explevels`
  src/haddock/__init__.py
  src/haddock/modules/analysis/caprieval/defaults.yaml
  src/haddock/modules/analysis/clustfcc/defaults.yaml
  src/haddock/modules/analysis/seletop/defaults.yaml
  src/haddock/modules/analysis/seletopclusts/defaults.yaml
  src/haddock/modules/defaults.yaml
  src/haddock/modules/refinement/emref/defaults.yaml
  src/haddock/modules/refinement/flexref/defaults.yaml
  src/haddock/modules/refinement/mdref/defaults.yaml
  src/haddock/modules/sampling/gdock/defaults.yaml
  src/haddock/modules/sampling/lightdock/defaults.yaml
  src/haddock/modules/sampling/rigidbody/defaults.yaml
  src/haddock/modules/scoring/emscoring/defaults.yaml
  src/haddock/modules/topology/topoaa/defaults.yaml
Labels: refactors

#308 Added description to topoaa default.yaml file
  examples/data/T161-rescoring-5.pdb
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape-full.cfg
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape-test.cfg
  src/haddock/modules/topology/topoaa/defaults.yaml
  tests/test_module_topoaa.py
Labels: documentation, m|topoaa

#310 update `pdbtools` dependencies
  requirements.txt
  requirements.yml
Labels: dependencies

#311 Update deps versions - forcing exact numbers
  requirements.txt
  requirements.yml
Labels: dependencies

#316 Add hierarchy to the categories
  src/haddock/modules/__init__.py
  tests/test_modules_general.py
Labels: enhance user experience

#315 Corrects explevels in `haddock3-cfg` choices
  src/haddock/clis/cli_cfg.py
  src/haddock/gear/yaml2cfg.py
  src/haddock/modules/topology/topoaa/defaults.yaml
  tests/configs/yml_example.yml
  tests/test_cli_cfg.py
  tests/test_yaml2cfg.py
Labels: bug

#319 Add unittests to `cns_paths` lib
  src/haddock/core/cns_paths.py
  tests/test_cns_paths.py
Labels: CI / repository

#318 Add YAML for mandatory parameters
  src/haddock/core/mandatory.yaml
  src/haddock/gear/parameters.py
  tests/test_mandatory_params.py
Labels: integration

#322 ignores `explvl = hidden`
  src/haddock/__init__.py
  src/haddock/gear/yaml2cfg.py
  tests/test_yaml2cfg.py
Labels: feature

#324 Corrects #322
  src/haddock/gear/yaml2cfg.py
  tests/test_yaml2cfg.py
Labels: bug

#325 Rigidbody yaml
  examples/docking-protein-DNA/docking-protein-DNA-full.cfg
  examples/docking-protein-DNA/docking-protein-DNA-mdref-full.cfg
  examples/docking-protein-DNA/docking-protein-DNA-mdref-test.cfg
  examples/docking-protein-DNA/docking-protein-DNA-test.cfg
  examples/docking-protein-homotrimer/docking-protein-homotrimer-full.cfg
  examples/docking-protein-homotrimer/docking-protein-homotrimer-test.cfg
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape-full.cfg
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape-test.cfg
  examples/docking-protein-ligand/docking-protein-ligand-full.cfg
  examples/docking-protein-ligand/docking-protein-ligand-test.cfg
  examples/docking-protein-peptide/docking-protein-peptide-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-mdref-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-mdref-test.cfg
  examples/docking-protein-peptide/docking-protein-peptide-test.cfg
  examples/docking-protein-protein/docking-protein-protein-cltsel-test.cfg
  examples/docking-protein-protein/docking-protein-protein-full.cfg
  examples/docking-protein-protein/docking-protein-protein-hpc-test.cfg
  examples/docking-protein-protein/docking-protein-protein-mdref-full.cfg
  examples/docking-protein-protein/docking-protein-protein-mdref-test.cfg
  examples/docking-protein-protein/docking-protein-protein-test.cfg
  src/haddock/modules/sampling/rigidbody/cns/bestener.cns
  src/haddock/modules/sampling/rigidbody/cns/cm-restraints.cns
  src/haddock/modules/sampling/rigidbody/cns/print_coorheader.cns
  src/haddock/modules/sampling/rigidbody/cns/read_noes.cns
  src/haddock/modules/sampling/rigidbody/cns/rigidbody.cns
  src/haddock/modules/sampling/rigidbody/cns/symmultimer.cns
  src/haddock/modules/sampling/rigidbody/defaults.yaml
Labels: CNS, m|rigidbody, yaml documentation

#326 corrects explvl
  src/haddock/modules/sampling/rigidbody/defaults.yaml
Labels: bug

#330 Emref yaml documentation and script cleaning
  examples/docking-protein-DNA/docking-protein-DNA-full.cfg
  examples/docking-protein-DNA/docking-protein-DNA-test.cfg
  examples/docking-protein-peptide/docking-protein-peptide-full.cfg
  src/haddock/modules/defaults.yaml
  src/haddock/modules/refinement/emref/cns/contactairs.cns
  src/haddock/modules/refinement/emref/cns/emref.cns
  src/haddock/modules/refinement/emref/cns/print_coorheader.cns
  src/haddock/modules/refinement/emref/cns/read_data.cns
  src/haddock/modules/refinement/emref/cns/read_noes.cns
  src/haddock/modules/refinement/emref/cns/setflags.cns
  src/haddock/modules/refinement/emref/defaults.yaml
  src/haddock/modules/sampling/rigidbody/defaults.yaml
Labels: m|emref, yaml documentation

#328 Reviews and updates `CONTRIBUTING`
  CONTRIBUTING.md
Labels: documentation

#323 Removing `prot_segid_*` from `yaml` configs
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape-full.cfg
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape-test.cfg
  src/haddock/libs/libcns.py
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/emref/defaults.yaml
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/flexref/defaults.yaml
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/refinement/mdref/defaults.yaml
  src/haddock/modules/sampling/rigidbody/__init__.py
  src/haddock/modules/sampling/rigidbody/defaults.yaml
Labels: enhancement, m|emref, m|flexref, m|mdref, m|rigidbody

#332 Mdref yaml documentation and CNS scripts updates
  examples/docking-protein-DNA/docking-protein-DNA-mdref-full.cfg
  examples/docking-protein-DNA/docking-protein-DNA-mdref-test.cfg
  examples/refine-complex/refine-complex-test.cfg
  src/haddock/modules/refinement/emref/cns/emref.cns
  src/haddock/modules/refinement/emref/defaults.yaml
  src/haddock/modules/refinement/mdref/cns/cm-restraints.cns
  src/haddock/modules/refinement/mdref/cns/contactairs.cns
  src/haddock/modules/refinement/mdref/cns/mdref.cns
  src/haddock/modules/refinement/mdref/cns/print_coorheader.cns
  src/haddock/modules/refinement/mdref/cns/read_data.cns
  src/haddock/modules/refinement/mdref/cns/read_noes.cns
  src/haddock/modules/refinement/mdref/cns/setflags.cns
  src/haddock/modules/refinement/mdref/cns/symmultimer.cns
  src/haddock/modules/refinement/mdref/defaults.yaml
Labels: m|mdref, yaml documentation

#335 Add elapsed time to modules and to the whole run
  src/haddock/clis/cli.py
  src/haddock/libs/libutil.py
  src/haddock/libs/libworkflow.py
  tests/test_libutil.py
Labels: feature
