Repository haddocking/haddock3, pull requests merged in 2022-08, with the labels that each got.

#525 Add action to deploy pages
  .github/workflows/pages.yml
Labels: CI / repository

#524 Updates docs theme to Karma theme
  devtools/docs-requirements.txt
  docs/conf.py
Labels: documentation

#527 Uses action to deploy pages
  .github/workflows/pages.yml
Labels: CI / repository

#530 add nojekyll file to GA generating pages
  .github/workflows/pages.yml
Labels: CI / repository, documentation

#531 Update guidelines to contribute to documentation
  CONTRIBUTING.md
  README.md
  src/haddock/gear/clean_steps.py
  src/haddock/gear/expandable_parameters.py
  src/haddock/libs/libstructure.py
  src/haddock/modules/refinement/emref/defaults.yaml
  src/haddock/modules/refinement/flexref/defaults.yaml
  src/haddock/modules/refinement/mdref/defaults.yaml
Labels: documentation

#520 Add template to write new modules
  CONTRIBUTING.md
  devtools/build_defaults_rst.py
  src/haddock/modules/_template_cat/README.md
  src/haddock/modules/_template_cat/_template_mod/__init__.py
  src/haddock/modules/_template_cat/_template_mod/defaults.yaml
  tox.ini
Labels: documentation

#533 Added support for 3-hydroxyproline (HY3)
  examples/scoring/data/HY3.pdb
  examples/scoring/emscoring-test.cfg
  src/haddock/cns/toppar/haddock.param-store
  src/haddock/cns/toppar/haddock.top-store
  src/haddock/cns/toppar/protein-allhdg5-4-noCter.link
  src/haddock/cns/toppar/protein-allhdg5-4-noNter.link
  src/haddock/cns/toppar/protein-allhdg5-4-noter.link
  src/haddock/cns/toppar/protein-allhdg5-4.link
  src/haddock/cns/toppar/protein-allhdg5-4.param
  src/haddock/cns/toppar/protein-allhdg5-4.top
  src/haddock/modules/refinement/emref/cns/restrain-ions.cns
  src/haddock/modules/refinement/flexref/cns/covalions.cns
  src/haddock/modules/refinement/flexref/cns/restrain-ions.cns
  src/haddock/modules/refinement/mdref/cns/restrain-ions.cns
  src/haddock/modules/sampling/rigidbody/cns/randomairs.cns
  src/haddock/modules/scoring/emscoring/cns/restrain-ions.cns
  src/haddock/modules/scoring/mdscoring/cns/restrain-ions.cns
  src/haddock/modules/topology/topoaa/cns/patch-types-cg.cns
Labels: enhancement, users, CNS

#522 Update the `--restart` option to cope with subfolders in steps.
  src/haddock/gear/prepare_run.py
  tests/__init__.py
  tests/data/0_dummystep/file1.in
  tests/data/0_dummystep/folder/file2.in
  tests/test_gear_prepare_run.py
Labels: :snake: workflow

#539 Add full support to `toml`
  docs/conf.py
  docs/reference/gear/config.rst
  docs/reference/gear/config_reader.rst
  docs/reference/gear/config_writer.rst
  docs/reference/gear/index.rst
  docs/tutorials/user_config.rst
  examples/compare_runs.py
  examples/docking-protein-protein/docking-exit-test.cfg
  examples/run_tests.py
  requirements.txt
  requirements.yml
  src/haddock/gear/config.py
  src/haddock/gear/config_reader.py
  src/haddock/gear/config_writer.py
  src/haddock/gear/prepare_run.py
  src/haddock/libs/libutil.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/__init__.py
  src/haddock/modules/refinement/emref/defaults.yaml
  src/haddock/modules/refinement/flexref/defaults.yaml
  src/haddock/modules/refinement/mdref/defaults.yaml
  src/haddock/modules/scoring/mdscoring/defaults.yaml
  tests/test_config_reader.py
  tests/test_examples_general.py
  tests/test_gear_config.py
  tests/test_gear_config_writer.py
  tests/test_gear_prepare_run.py
  tests/test_libutil.py
  tests/test_modules_general.py
  tox.ini
Labels: feature, :snake: workflow

#540 Update the `docs` badge to match the `pages.yml` file.
  README.md
Labels: CI / repository
