Repository haddocking/haddock3, pull requests merged in 2022-04, with the labels that each got.

#368 Install fcc over https
  requirements.txt
Labels: dependencies

#374 Read yaml should return always a dictionary
  src/haddock/libs/libio.py
  tests/__init__.py
  tests/configs/empty.cfg
  tests/test_libio.py
Labels: bug

#377 removes requirement of docstrings in tests
  tox.ini
Labels: CI / repository

#379 Max number of molecules defined in a single place - the config
  src/haddock/__init__.py
  src/haddock/core/defaults.py
  tests/test_core.py
Labels: refactors

#378 Zerofill
  src/haddock/libs/libutil.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/__init__.py
  tests/test_libutil.py
Labels: enhancement, enhance user experience

#383 Corrects edge case in zero filling modules folder names
  src/haddock/libs/libutil.py
  src/haddock/libs/libworkflow.py
  tests/test_libutil.py
Labels: bug

#391 Lifts `zero fill` logic to `gear`
  src/haddock/gear/prepare_run.py
  src/haddock/gear/zerofill.py
  src/haddock/libs/libutil.py
  src/haddock/libs/libworkflow.py
  tests/test_gear_zerofill.py
  tests/test_libutil.py
Labels: refactors

#390 Improve docs and tests for a part of the `setup_run` function
  src/haddock/gear/expandable_parameters.py
  src/haddock/gear/prepare_run.py
  tests/test_gear_expandable_parameters.py
Labels: documentation, :fire:, :godmode:

#389 modules prefix to defaults
  src/haddock/core/defaults.py
  src/haddock/gear/restart_run.py
  src/haddock/modules/__init__.py
Labels: bug, enhancement

#385 Caprieval parallel
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/caprieval/capri.py
  src/haddock/modules/analysis/caprieval/caprijob.py
  tests/test_module_caprieval.py
Labels: feature, m|caprieval

#399 Ignore `WAT` residues in `caprieval`
  src/haddock/modules/analysis/caprieval/capri.py
Labels: enhancement, m|caprieval

#401 Remove solvent molecules from the output of `mdscoring`
  examples/scoring/mdscoring-test.cfg
  src/haddock/modules/scoring/mdscoring/cns/mdscoring.cns
Labels: CNS, m|mdscoring

#404 Bugfix for numbering reference between model and receptor
  src/haddock/modules/analysis/caprieval/capri.py
  tests/test_module_caprieval.py
Labels: m|caprieval

#410 Correct small (future) bug in reading `self_contained` parameter
  src/haddock/modules/base_cns_module.py
  tests/test_libutil.py
Labels: bug

#397 added input output dictionary in scoring modules
  examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-test.cfg
  examples/run_tests.py
  examples/scoring/emscoring-mdscoring-test.cfg
  src/haddock/modules/scoring/__init__.py
  src/haddock/modules/scoring/emscoring/__init__.py
  src/haddock/modules/scoring/mdscoring/__init__.py
  tests/test_module_emscoring.py
  tests/test_module_mdscoring.py
Labels: bug, m|emscoring, m|mdscoring

#412 added missing os
  examples/run_tests.py
  tox.ini
Labels: bug, CI / repository

#415 amend threshold behavior in clustfcc
  src/haddock/modules/analysis/clustfcc/__init__.py
Labels: bug, m|clustfcc
