Repository haddocking/haddock3, pull requests merged in 2022-01, with the labels that each got.

#246 Validates module's name
  src/haddock/gear/prepare_run.py
Labels: bug

#238 add run examples scripts
  examples/run_examples.py
Labels: feature

#256 corrects dictionary to tuple of tuples in `run_examples.py`
  examples/run_examples.py
Labels: bug

#250 Add `ori_names` to `PDBobject`
  src/haddock/libs/libontology.py
  src/haddock/modules/topology/topoaa/__init__.py
Labels: feature

#258 Fixes issue #257
  src/haddock/modules/topology/topoaa/cns/generate-topology.cns
Labels: bug

#255 Implement automatic threshold in `clustfcc`
  examples/docking-protein-protein/docking-protein-protein.cfg
  src/haddock/modules/analysis/clustfcc/__init__.py
Labels: feature

#261 No limit of 20 molecules for `topoaa`
  src/haddock/modules/topology/topoaa/__init__.py
  src/haddock/modules/topology/topoaa/defaults.cfg
Labels: enhancement

#263 Update `libhpc`
  examples/docking-protein-protein/docking-protein-protein-hpc.cfg
  src/haddock/libs/libhpc.py
Labels: bug

#266 Implement `lt`, `gt` and `eq` operators to `PDBFile`
  src/haddock/libs/libontology.py
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/clustfcc/__init__.py
Labels: enhancement, m|caprieval, m|clustfcc

#248 Update `seletopclusts` with the newest changes
  examples/docking-protein-protein/docking-protein-protein-cltsel.cfg
  examples/run_examples.py
  src/haddock/modules/analysis/seletopclusts/__init__.py
Labels: enhancement, m|seletopclusts

#267 Implemented `JobInputFirst`
  src/haddock/libs/libsubprocess.py
  src/haddock/modules/analysis/clustfcc/__init__.py
Labels: execution, refactors

#268 Refactored the parameter flow
  src/haddock/__init__.py
  src/haddock/gear/parameters.py
  src/haddock/gear/prepare_run.py
  src/haddock/libs/libhpc.py
  src/haddock/libs/libutil.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/__init__.py
  src/haddock/modules/base_cns_module.py
  src/haddock/modules/defaults.cfg
  tests/test_libutil.py
Labels: refactors

#286 Add option to select all clusters in `seletopclusts`
  examples/docking-protein-protein/docking-protein-protein-cltsel.cfg
  src/haddock/modules/analysis/seletopclusts/__init__.py
  src/haddock/modules/analysis/seletopclusts/defaults.cfg
Labels: m|seletopclusts

#287 Add dockq metric to `caprieval`
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/caprieval/capri.py
Labels: m|caprieval

#291 Added full sampling cfg files
  examples/docking-protein-DNA/docking-protein-DNA-full.cfg
  examples/docking-protein-DNA/docking-protein-DNA-mdref-full.cfg
  examples/docking-protein-DNA/docking-protein-DNA-mdref-test.cfg
  examples/docking-protein-DNA/docking-protein-DNA-test.cfg
  examples/docking-protein-homotrimer/docking-protein-homotrimer-full.cfg
  examples/docking-protein-homotrimer/docking-protein-homotrimer-test.cfg
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape-full.cfg
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape-test.cfg
  examples/docking-protein-ligand/docking-protein-ligand-full.cfg
  examples/docking-protein-ligand/docking-protein-ligand-test.cfg
  examples/docking-protein-peptide/docking-protein-peptide-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-test.cfg
  examples/docking-protein-protein/docking-protein-protein-cltsel-test.cfg
  examples/docking-protein-protein/docking-protein-protein-full.cfg
  examples/docking-protein-protein/docking-protein-protein-hpc-test.cfg
  examples/docking-protein-protein/docking-protein-protein-mdref-full.cfg
  examples/docking-protein-protein/docking-protein-protein-mdref-test.cfg
  examples/docking-protein-protein/docking-protein-protein-test.cfg
  examples/refine-complex/refine-complex-test.cfg
  examples/run_examples-full.py
  examples/run_tests.py
  examples/scoring/scoring-test.cfg
Labels: enhancement

#295 Update modules to pass the correct variable to `ModuleIO`
  src/haddock/libs/libontology.py
  src/haddock/modules/refinement/emref/__init__.py
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/mdref/__init__.py
  src/haddock/modules/scoring/emscoring/__init__.py
Labels: bug, m|emscoring, m|emref, m|flexref, m|mdref

#300 Remove `input` layer in `topoaa` module.
  examples/docking-protein-homotrimer/docking-protein-homotrimer-full.cfg
  examples/docking-protein-homotrimer/docking-protein-homotrimer-test.cfg
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape-full.cfg
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape-test.cfg
  examples/docking-protein-peptide/docking-protein-peptide-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-mdref-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-mdref-test.cfg
  examples/docking-protein-peptide/docking-protein-peptide-test.cfg
  examples/docking-protein-protein/docking-protein-protein-cltsel-test.cfg
  examples/docking-protein-protein/docking-protein-protein-full.cfg
  examples/docking-protein-protein/docking-protein-protein-hpc-test.cfg
  examples/docking-protein-protein/docking-protein-protein-mdref-full.cfg
  examples/docking-protein-protein/docking-protein-protein-mdref-test.cfg
  examples/docking-protein-protein/docking-protein-protein-test.cfg
  examples/refine-complex/refine-complex-test.cfg
  src/haddock/modules/topology/topoaa/__init__.py
  src/haddock/modules/topology/topoaa/defaults.cfg
Labels: m|topoaa

#298 [REDO] Set tolerance of modules in the workflow integration tests to 20%
  examples/docking-protein-DNA/docking-protein-DNA-mdref-test.cfg
  examples/docking-protein-DNA/docking-protein-DNA-test.cfg
  examples/docking-protein-homotrimer/docking-protein-homotrimer-test.cfg
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape-test.cfg
  examples/docking-protein-ligand/docking-protein-ligand-test.cfg
  examples/docking-protein-peptide/docking-protein-peptide-mdref-test.cfg
  examples/docking-protein-peptide/docking-protein-peptide-test.cfg
  examples/docking-protein-protein/docking-protein-protein-cltsel-test.cfg
  examples/docking-protein-protein/docking-protein-protein-hpc-test.cfg
  examples/docking-protein-protein/docking-protein-protein-mdref-test.cfg
  examples/docking-protein-protein/docking-protein-protein-test.cfg
  examples/refine-complex/refine-complex-test.cfg
  examples/scoring/scoring-test.cfg
Labels: enhancement, documentation
