Repository haddocking/haddock3, pull requests merged in 2022-12, with the labels that each got.

#594 Compress `.inp`, `.out`, and `.seed` in CNS Jobs on the fly
  docs/clients/cliclean.rst
  docs/clients/cliunpack.rst
  src/haddock/clis/cli_clean.py
  src/haddock/clis/cli_cp.py
  src/haddock/clis/cli_unpack.py
  src/haddock/gear/clean_steps.py
  src/haddock/gear/extend_run.py
  src/haddock/gear/prepare_run.py
  src/haddock/libs/libio.py
  src/haddock/libs/libsubprocess.py
  src/haddock/libs/libworkflow.py
  tests/test_gear_clean_steps.py
  tests/test_libio.py
Labels: enhancement, enhance user experience

#597 Implement option to use MAX CPUs and bypass the `N-1` rule for `local` mode.
  src/haddock/libs/libparallel.py
  src/haddock/libs/libutil.py
  src/haddock/modules/__init__.py
  src/haddock/modules/defaults.yaml
  tests/test_libutil.py
Labels: enhancement, yaml default parameters, :godmode:, :snake: workflow

#599 add `w+` to data dir
  src/haddock/gear/prepare_run.py
  src/haddock/libs/libio.py
Labels: enhancement

#600 Related to issue #598 - now compatible with OSX as well
  src/haddock/libs/libio.py
Labels: bug
