Repository haddocking/haddock3, pull requests merged in 2023-12, with the labels that each got.

#758 show gzipped structures in analysis report
  src/haddock/clis/cli_analyse.py
  src/haddock/libs/libplots.py
  src/haddock/libs/libworkflow.py
  tests/test_cli_analyse.py
  tests/test_libworkflow.py
Labels: bug, analysis/postprocessing

#764 modif float comparisons in contact map tests
  tests/test_module_contmap.py
Labels: enhancement, m|contactmap

#768 updated protein-peptide example and test config file - issue #767
  examples/docking-protein-peptide/docking-protein-peptide-cltsel-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-mdref-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-mdref-test.cfg
  examples/docking-protein-peptide/docking-protein-peptide-test.cfg
Labels: examples
