Repository haddocking/haddock3, pull requests merged in 2024-03, with the labels that each got.

#727 Mapping TIMEOUT output to failure in libhpc
  src/haddock/libs/libhpc.py
  tests/test_libhpc.py
Labels: enhancement, execution

#807 corrected parameter handling for cli-score
  integration_tests/test_cli_score.py
  src/haddock/clis/cli_score.py
Labels: bug

#828 Work arround chain matching in IL-RMSDMatrix
  src/haddock/libs/libalign.py
  src/haddock/modules/analysis/ilrmsdmatrix/ilrmsd.py
  tests/test_libalign.py
Labels: bug, m|ilrmsdmatrix

#831 ordered traceback
  examples/compare_runs.py
  examples/run_tests.py
  src/haddock/clis/cli_traceback.py
  tests/test_cli_traceback.py
Labels: enhancement, analysis/postprocessing
