Repository haddocking/haddock3, pull requests merged in 2024-04, with the labels that each got.

#847 Resolves issue #845 - adding missing parameters
  src/haddock/cns/toppar/protein-allhdg5-4-noCter.link
  src/haddock/cns/toppar/protein-allhdg5-4-noNter.link
  src/haddock/cns/toppar/protein-allhdg5-4-noter.link
  src/haddock/cns/toppar/protein-allhdg5-4.link
  src/haddock/cns/toppar/protein-allhdg5-4.param
  src/haddock/cns/toppar/protein-allhdg5-4.top
Labels: community, parameters-topologies

#823 Interactivity fixes
  examples/docking-protein-protein/docking-protein-protein-cltsel-full.cfg
  src/haddock/clis/cli_analyse.py
  src/haddock/clis/re/clustfcc.py
  src/haddock/clis/re/score.py
  src/haddock/libs/libinteractive.py
  src/haddock/modules/analysis/alascan/scan.py
  src/haddock/modules/analysis/seletopclusts/__init__.py
  src/haddock/modules/sampling/rigidbody/__init__.py
  tests/test_cli_re.py
  tests/test_libinteractive.py
Labels: bug, integration, workflow

#772 Graphical representation of clusters
  examples/analysis/data/ensemble_4G6M.pdb
  examples/analysis/data/target.pdb
  examples/analysis/plot-finetune-clustfcc.cfg
  examples/analysis/plot-finetune-ilrmsdmatrix-clustrmsd.cfg
  examples/analysis/topoaa-clustfcc-test.cfg
  examples/analysis/topoaa-ilrmsdmatrix-clustrmsd-test.cfg
  src/haddock/libs/libclust.py
  src/haddock/libs/libplots.py
  src/haddock/modules/analysis/clustfcc/__init__.py
  src/haddock/modules/analysis/clustfcc/defaults.yaml
  src/haddock/modules/analysis/clustrmsd/__init__.py
  src/haddock/modules/analysis/clustrmsd/clustrmsd.py
  src/haddock/modules/analysis/clustrmsd/defaults.yaml
  src/haddock/modules/analysis/ilrmsdmatrix/__init__.py
  tests/test_libclust.py
Labels: enhancement, m|clustfcc, examples, m|clustrmsd

#850 added traceback plot and sum of ranks file
  src/haddock/clis/cli_traceback.py
  src/haddock/libs/libplots.py
  tests/test_cli_traceback.py
Labels: enhancement, analysis/postprocessing

#825 Offline mode
  src/haddock/clis/cli_analyse.py
  src/haddock/libs/libplots.py
  src/haddock/libs/libworkflow.py
  src/haddock/modules/analysis/alascan/__init__.py
  src/haddock/modules/analysis/alascan/scan.py
  src/haddock/modules/analysis/contactmap/__init__.py
  src/haddock/modules/analysis/contactmap/contmap.py
  src/haddock/modules/defaults.yaml
  tests/test_libplots.py
  tests/test_libworkflow.py
  tests/test_module_contmap.py
  tests/test_modules_analysis.py
Labels: enhancement, security

#854 Fix offlinemode
  src/haddock/libs/libplots.py
Labels: bug

#855 Upgrade contact heatmap
  src/haddock/modules/analysis/contactmap/contmap.py
Labels: enhancement

#851 Fixing error in caprieval using shapes
  src/haddock/libs/libalign.py
Labels: bug, m|caprieval

#853 Fix auto analysis
  examples/compare_runs.py
  examples/run_tests.py
  src/haddock/core/defaults.py
  src/haddock/modules/analysis/caprieval/__init__.py
  src/haddock/modules/analysis/caprieval/capri.py
  tests/test_module_caprieval.py
Labels: bug, analysis/postprocessing

#819 Improved seletopclusts
  examples/analysis/seletopclusts.cfg
  src/haddock/modules/analysis/seletopclusts/__init__.py
  src/haddock/modules/analysis/seletopclusts/defaults.yaml
  src/haddock/modules/analysis/seletopclusts/seletopclusts.py
  tests/test_module_seletopclusts.py
Labels: enhancement, m|seletopclusts

#864 Chain match coords load issue
  src/haddock/libs/libalign.py
  src/haddock/modules/analysis/caprieval/capri.py
Labels: bug

#868 Fair
  CITATION.cff
  README.md
Labels: CI / repository

#876 Added alascan modules to tests execution and comparison
  examples/compare_runs.py
  examples/run_tests.py
Labels: m|alascan

#878 Add prefix to model names from input ensemble
  src/haddock/modules/topology/topoaa/__init__.py
Labels: enhancement, m|topoaa

#880 Save outputs in case of faulty tolerance
  src/haddock/modules/__init__.py
Labels: enhancement

#837 Heavy atoms RMSD calculation in caprieval
  examples/docking-protein-DNA/docking-protein-DNA-cltsel-full.cfg
  examples/docking-protein-DNA/docking-protein-DNA-full.cfg
  examples/docking-protein-DNA/docking-protein-DNA-mdref-full.cfg
  examples/docking-protein-DNA/docking-protein-DNA-mdref-test.cfg
  examples/docking-protein-DNA/docking-protein-DNA-test.cfg
  examples/docking-protein-glycan/docking-flexref-protein-glycan-full.cfg
  examples/docking-protein-glycan/docking-flexref-protein-glycan-test.cfg
  examples/docking-protein-glycan/docking-protein-glycan-full.cfg
  examples/docking-protein-glycan/docking-protein-glycan-ilrmsd-full.cfg
  examples/docking-protein-glycan/docking-protein-glycan-ilrmsd-test.cfg
  examples/docking-protein-glycan/docking-protein-glycan-test.cfg
  examples/docking-protein-ligand/docking-protein-ligand-full.cfg
  examples/docking-protein-ligand/docking-protein-ligand-test.cfg
  examples/docking-protein-peptide/docking-protein-peptide-cltsel-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-mdref-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-mdref-test.cfg
  examples/docking-protein-peptide/docking-protein-peptide-test.cfg
  src/haddock/libs/libalign.py
  src/haddock/modules/analysis/caprieval/capri.py
  src/haddock/modules/analysis/caprieval/defaults.yaml
  tests/test_module_caprieval.py
Labels: enhancement, m|caprieval, community
