Repository haddocking/haddock3, pull requests merged in 2024-10, with the labels that each got.

#991 Parameter incompatibilities: Increase flexibility in incompatibilities handles.
  src/haddock/gear/prepare_run.py
  src/haddock/modules/defaults.yaml
  tests/test_gear_prepare_run.py
Labels: bug, execution

#1071 Corrected incompatibility values for the debug parameter
  examples/docking-antibody-antigen/docking-antibody-antigen-CDR-NMR-CSP-full.cfg
  examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-clt-full.cfg
  examples/docking-antibody-antigen/docking-antibody-antigen-CDR-accessible-full.cfg
  examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-clt-full.cfg
  examples/docking-antibody-antigen/docking-antibody-antigen-ranairCDR-full.cfg
  examples/docking-multiple-ambig/docking-multiple-tbls-clt-full.cfg
  examples/docking-protein-DNA/docking-protein-DNA-cltsel-full.cfg
  examples/docking-protein-DNA/docking-protein-DNA-full.cfg
  examples/docking-protein-DNA/docking-protein-DNA-mdref-full.cfg
  examples/docking-protein-glycan/docking-flexref-protein-glycan-full.cfg
  examples/docking-protein-glycan/docking-protein-glycan-full.cfg
  examples/docking-protein-homotrimer/docking-protein-homotrimer-full.cfg
  examples/docking-protein-ligand-shape/docking-protein-ligand-shape-full.cfg
  examples/docking-protein-ligand/docking-protein-ligand-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-cltsel-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-full.cfg
  examples/docking-protein-peptide/docking-protein-peptide-mdref-full.cfg
  examples/docking-protein-protein/docking-protein-protein-cltsel-full.cfg
  examples/docking-protein-protein/docking-protein-protein-full.cfg
  examples/docking-protein-protein/docking-protein-protein-hpc-test.cfg
  examples/docking-protein-protein/docking-protein-protein-mdref-full.cfg
  src/haddock/modules/defaults.yaml
Labels: yaml default parameters

#1041 Import plotly offline mode
  src/haddock/clis/cli_analyse.py
  src/haddock/clis/cli_traceback.py
  src/haddock/libs/libplots.py
  src/haddock/libs/libworkflow.py
  tests/test_libplots.py
Labels: enhancement

#1073 add integration test stub for ATTRACT integration
  integration_tests/__init__.py
  integration_tests/golden_data/rna.pdb
  integration_tests/test_attract.py
Labels: CI / repository, m|attract

#1025 Replace haddock3-analysis-components with haddock3-ui package
  MANIFEST.in
  pyproject.toml
  src/haddock/clis/cli_analyse.py
  src/haddock/libs/assets/__init__.py
  src/haddock/libs/assets/index.css
  src/haddock/libs/assets/report.bundle.js
  src/haddock/libs/libplots.py
  tests/test_cli_analyse.py
Labels: enhancement

#482 Add OpenMM module
  docs/INSTALL.md
  examples/thirdparty/openmm/data/1NX1_protein.pdb
  examples/thirdparty/openmm/data/1nx1_refe.pdb
  examples/thirdparty/openmm/data/DAIDALSSDFT_3conformations.pdb
  examples/thirdparty/openmm/data/DAIDALSSDFT_alpha.pdb
  examples/thirdparty/openmm/data/DAIDALSSDFT_ext.pdb
  examples/thirdparty/openmm/data/DAIDALSSDFT_polyII.pdb
  examples/thirdparty/openmm/data/ambig.tbl
  examples/thirdparty/openmm/openmm-complex-refinement.cfg
  examples/thirdparty/openmm/openmm-implicit-solvent-test.cfg
  examples/thirdparty/openmm/openmm-test.cfg
  examples/thirdparty/openmm/openmm-topoaa-flexref-test.cfg
  src/haddock/core/exceptions.py
  src/haddock/modules/__init__.py
  src/haddock/modules/refinement/openmm/__init__.py
  src/haddock/modules/refinement/openmm/defaults.yaml
  src/haddock/modules/refinement/openmm/openmm.py
  tests/test_examples_general.py
Labels: feature, m|openmm

#1075 limiting cpu usage in `[openmm]`
  src/haddock/modules/refinement/openmm/__init__.py
Labels: bug, execution

#1085 Add pipeline to publish image to `ghcr.io`
  .github/workflows/docker-publish.yml
  Dockerfile
Labels: CI / repository

#1087 add pipeline to automatically publish package in `pypi` on every release
  .github/workflows/publish.yml
  README.md
  pyproject.toml
Labels: CI / repository

#1086 Workaround plotly / kaleido static figure generation
  pyproject.toml
  src/haddock/clis/cli_analyse.py
  src/haddock/libs/libclust.py
  src/haddock/libs/libfunc.py
  src/haddock/libs/libplots.py
  src/haddock/modules/analysis/clustfcc/__init__.py
  src/haddock/modules/analysis/clustrmsd/__init__.py
  tests/test_libclust.py
  tests/test_libplots.py
Labels: enhancement

#862 sasascore module
  devtools/build_defaults_rst.py
  examples/scoring/sasascore-test.cfg
  integration_tests/test_sasascore.py
  src/haddock/clis/restraints/calc_accessibility.py
  src/haddock/libs/librestraints.py
  src/haddock/modules/analysis/__init__.py
  src/haddock/modules/scoring/sasascore/__init__.py
  src/haddock/modules/scoring/sasascore/defaults.yaml
  src/haddock/modules/scoring/sasascore/sasascore.py
  tests/test_module_caprieval.py
  tests/test_module_sasascore.py
Labels: enhancement, community, m|accscoring

#1103 Remove adaptative sleep logic in libhpc
  src/haddock/libs/libhpc.py
Labels: execution

#1090 Correction of the usage of DSSP in the topocg module
  src/haddock/modules/topology/topocg/aa2cg.py
  src/haddock/modules/topology/topocg/helper.py
Labels: m|topocg

#1109 Correct auto documentation
  .github/workflows/pages.yml
  .readthedocs.yml
  devtools/build_defaults_rst.py
  docs/tutorials/benchmark.md
  pyproject.toml
  src/haddock/modules/refinement/flexref/__init__.py
  src/haddock/modules/refinement/openmm/__init__.py
  src/haddock/modules/refinement/openmm/openmm.py
Labels: documentation

#1123 Fix tests
  .github/workflows/ci.yml
  integration_tests/test_knownCNSerrors.py
  integration_tests/test_sasascore.py
  pyproject.toml
  src/haddock/modules/scoring/sasascore/__init__.py
  src/haddock/modules/scoring/sasascore/sasascore.py
  tests/test_cli_analyse.py
  tests/test_cli_re.py
  tests/test_cli_restraints.py
  tests/test_cli_traceback.py
  tests/test_gear_preprocessing.py
  tests/test_libalign.py
  tests/test_libplots.py
  tests/test_module_alascan.py
  tests/test_module_caprieval.py
  tests/test_module_clustfcc.py
  tests/test_module_clustrmsd.py
  tests/test_module_contmap.py
  tests/test_module_emscoring.py
  tests/test_module_flexref.py
  tests/test_module_ilrmsdmatrix.py
  tests/test_module_mdscoring.py
  tests/test_module_rigidbody.py
  tests/test_module_rmsdmatrix.py
  tests/test_module_sasascore.py
  tests/test_module_seletopclusts.py
  tests/test_module_topoaa.py
  tests/test_modules_general.py
Labels: bug, CI / repository
