Repository haddocking/haddock3, pull requests merged in 2024-11, with the labels that each got.

#1129 fix random error
  tests/test_module_caprieval.py
Labels: bug, m|caprieval

#1120 Analysis not capri
  integration_tests/test_full_workflow.py
  src/haddock/clis/cli_analyse.py
Labels: bug, analysis/postprocessing

#1124 fixed analysis on cleaned, downloaded runs
  integration_tests/golden_data/workflow.cfg
  integration_tests/test_full_workflow.py
  src/haddock/clis/cli_analyse.py
Labels: bug, analysis/postprocessing

#1138 caught CNS exception in scoring modules
  src/haddock/modules/scoring/__init__.py
  src/haddock/modules/scoring/emscoring/__init__.py
  src/haddock/modules/scoring/mdscoring/__init__.py
Labels: bug, m|emscoring, m|mdscoring

#1134 add new glycans
  src/haddock/cns/toppar/carbohydrate.param
  src/haddock/cns/toppar/carbohydrate.top
  src/haddock/modules/topology/topoaa/cns/bondglycans.cns
Labels: CNS, parameters-topologies

#1156 Create validate_citation.yml
  .github/workflows/validate_citation.yml
  CITATION.cff
Labels: enhancement, documentation

#1161 adding bioexcel forum
  src/haddock/gear/greetings.py
Labels: enhancement
