Repository haddocking/haddock3, pull requests merged in 2025-07, with the labels that each got.

#1294 Added separate mpi install option
  .github/workflows/ci.yml
  DEVELOPMENT.md
  README.md
  docs/INSTALL.md
  integration_tests/__init__.py
  integration_tests/test_mpi.py
  integration_tests/test_rigidbody.py
  pyproject.toml
Labels: CI / repository

#1316 Fix restrain lig test
  src/haddock/clis/restraints/restrain_ligand.py
Labels: bug, CI / repository

#1334 computing std dev in alascan
  CHANGELOG.md
  integration_tests/test_alascan.py
  src/haddock/libs/libplots.py
  src/haddock/modules/analysis/alascan/scan.py
  tests/test_libplots.py
  tests/test_module_alascan.py
Labels: enhancement, m|alascan
