Repository haddocking/haddock3, pull requests merged in 2025-06, with the labels that each got.

#1273 Selection of Nter, Cter and 5'end states at topology generation
  integration_tests/golden_data/mini_dna.pdb
  integration_tests/test_topoaa.py
  src/haddock/cns/toppar/ligand.param
  src/haddock/cns/toppar/ligand.pep
  src/haddock/cns/toppar/ligand.top
  src/haddock/cns/toppar/shape.link
  src/haddock/core/cns_paths.py
  src/haddock/libs/libcns.py
  src/haddock/modules/refinement/emref/cns/read_param.cns
  src/haddock/modules/refinement/flexref/cns/read_param.cns
  src/haddock/modules/refinement/mdref/cns/read_param.cns
  src/haddock/modules/sampling/rigidbody/cns/read_param.cns
  src/haddock/modules/scoring/emscoring/cns/read_param.cns
  src/haddock/modules/scoring/mdscoring/cns/read_param.cns
  src/haddock/modules/topology/topoaa/__init__.py
  src/haddock/modules/topology/topoaa/cns/generate-topology.cns
  src/haddock/modules/topology/topoaa/defaults.yaml
Labels: CNS, m|topoaa

#1290 Added support for pyroglutamic acid - issue #1228
  CHANGELOG.md
  src/haddock/cns/toppar/protein-allhdg5-4-noCter.link
  src/haddock/cns/toppar/protein-allhdg5-4-noNter.link
  src/haddock/cns/toppar/protein-allhdg5-4-noter.link
  src/haddock/cns/toppar/protein-allhdg5-4.link
  src/haddock/cns/toppar/protein-allhdg5-4.param
  src/haddock/cns/toppar/protein-allhdg5-4.top
Labels: enhancement, parameters-topologies

#1297 make deepcopy of molecule params so they can be used multiple times
  src/haddock/modules/topology/topoaa/__init__.py
Labels: bug

#1301 Restrain ligand
  CHANGELOG.md
  src/haddock/clis/cli_restraints.py
  src/haddock/clis/restraints/restrain_ligand.py
  tests/test_cli_restraints.py
Labels: feature, community

#1304 adding citruline parameters/topology definition
  integration_tests/test_alascan.py
  src/haddock/cns/toppar/protein-allhdg5-4-noCter.link
  src/haddock/cns/toppar/protein-allhdg5-4-noNter.link
  src/haddock/cns/toppar/protein-allhdg5-4-noter.link
  src/haddock/cns/toppar/protein-allhdg5-4.link
  src/haddock/cns/toppar/protein-allhdg5-4.param
  src/haddock/cns/toppar/protein-allhdg5-4.top
  src/haddock/modules/analysis/alascan/__init__.py
  src/haddock/modules/analysis/alascan/defaults.yaml
  src/haddock/modules/analysis/alascan/scan.py
Labels: parameters-topologies
