Repository haddocking/haddock3, pull requests merged in 2025-02, with the labels that each got.

#1197 Added CNS troubleshooting instructions (issue #1191)
  DEVELOPMENT.md
  docs/INSTALL.md
Labels: documentation

#1199 removed debug log calls
  src/haddock/libs/libalign.py
  src/haddock/modules/analysis/caprieval/capri.py
Labels: enhancement, m|caprieval

#1206 Add radius passive from active
  src/haddock/clis/cli_restraints.py
  src/haddock/clis/restraints/passive_from_active.py
Labels: enhancement
