Repository haddocking/haddock3, pull requests merged in 2025-09, with the labels that each got.

#1368 add `libnotebooks`
  .github/workflows/ci.yml
  pyproject.toml
  src/haddock/libs/libnotebooks.py
  tests/__init__.py
  tests/test_libnotebooks.py
Labels: enhancement

#1376 Adding the notebooks directory
  CHANGELOG.md
  notebooks/HADDOCK3-antibody-antigen.ipynb
  notebooks/README.md
  pyproject.toml
Labels: feature, community

#1386 update minimum `mpi4py` version
  pyproject.toml
Labels: execution, dependencies

#1400 Cleaned the antibody-antigen notebook
  notebooks/HADDOCK3-antibody-antigen.ipynb
Labels: notebooks

#1402 Corrected dead links
  notebooks/HADDOCK3-antibody-antigen.ipynb
Labels: notebooks
